---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loki-stack-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./applications/loki-stack/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  dependsOn:
    - name: loki-stack-repo
    - name: kube-prometheus-stack-app
