---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfs-provisioner-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./applications/nfs-provisioner/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-infrastructure
  dependsOn:
    - name: nfs-provisioner-repo
