---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-repo
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./repositories/nextcloud/base
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-workloads
