---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: monitoring
spec:
  uninstall:
    keepHistory: false
    disableHooks: false
    deletionPropagation: foreground
  interval: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: loki-stack
      version: 2.9.12
      sourceRef:
        kind: HelmRepository
        name: loki-stack
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: helm-values-override
      valuesKey: values.yaml
      optional: true
    - kind: Secret
      name: helm-sensitive-values
      valuesKey: values.secrets.yaml
      optional: true
