---
# https://artifacthub.io/packages/helm/cert-manager/cert-manager
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  interval: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: cert-manager
      # upgrade path: 1.15.5 -> 1.16.5 -> 1.17.4 -> 1.18.4 -> 1.19.2
      version: 1.19.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: helm-values-override
      valuesKey: values.yaml
      optional: true
    - kind: Secret
      name: helm-sensitive-values
      valuesKey: values.secrets.yaml
      optional: true
