---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wiki
  namespace: wiki
spec:
  interval: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: wiki
      version: 2.2.24
      sourceRef:
        kind: HelmRepository
        name: wiki
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: helm-values-override
      valuesKey: values.yaml
      optional: true
    - kind: Secret
      name: helm-sensitive-values
      valuesKey: values.secrets.yaml
      optional: true
