---
# https://artifacthub.io/packages/helm/vmware-tanzu/velero
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 10m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: velero
      # upgrade path: 3.1.6 -> 4.0.3 -> 5.4.1 -> 6.7.0 -> 7.2.2 -> 8.7.2 -> 9.2.0 -> 10.1.3 -> 11.2.0
      version: 11.2.0
      sourceRef:
        kind: HelmRepository
        name: velero
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: helm-values-override
      valuesKey: values.yaml
      optional: true
    - kind: Secret
      name: helm-sensitive-values
      valuesKey: values.secrets.yaml
      optional: true
