---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: keycloak-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./applications/keycloak/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-workloads
  dependsOn:
    - name: keycloak-repo
