---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wiki-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./applications/wiki/overlays/winfra-prod
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-workloads
  dependsOn:
    - name: wiki-repo
