---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nextcloud-app
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./applications/nextcloud/overlays/winfra-test
  prune: true
  force: false
  sourceRef:
    kind: GitRepository
    name: flux-workloads
  dependsOn:
    - name: nextcloud-repo
