---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/grafana/helm-charts/grafana
  ref:
    tag: 10.4.0
