---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: mimir-distributed
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/grafana/helm-charts/mimir-distributed
  ref:
    tag: 5.8.0
