---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: loki
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/grafana/helm-charts/loki
  ref:
    tag: 6.49.0
