---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 5m0s
  timeout: 15m0s
  driftDetection:
    mode: enabled
  uninstall:
    keepHistory: false
    disableHooks: false
    deletionPropagation: foreground
  chart:
    spec:
      chart: nextcloud
      version: 8.7.0
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: helm-values
      valuesKey: values.yaml
    - kind: ConfigMap
      name: helm-values-override
      valuesKey: values.yaml
      optional: true
    - kind: Secret
      name: helm-sensitive-values
      valuesKey: values.secrets.yaml
      optional: true