apiVersion: v1
kind: Pod
metadata:
  name: redis-debug
  namespace: gitlab
spec:
  restartPolicy: Never
  containers:
  - name: debug
    image: busybox:1.36
    command: ["sh", "-c", "sleep 3600"]
    volumeMounts:
    - mountPath: /data
      name: redis-data
  volumes:
  - name: redis-data
    persistentVolumeClaim:
      claimName: redis-data-gitlab-redis-master-0

